### PR TITLE
csharp flag added to protobuf

### PR DESCRIPTION
**Pull request by KarlaCarvajal**
- Add csharp flag to generate sdk-dotnet models

### CODE REVIEW

**Comment by eduwercamacaro** [comment]
I think you should push the generated classes too. This might change in the future though. @mijailr  what do you think?

**Comment by KarlaCarvajal** [comment]
> I think you should push the generated classes too. This might change in the future though. @mijailr what do you think?

I was going to upload the generated files when the dotnet-sdk were fix, in a new branch

**Comment by mijailr** [comment]
Yeah it's fine. We want to remove the generated files from the repo but that will be done later.

**Review by sauljabin — APPROVED** [review]

**Comment by KarlaCarvajal** [comment]
There was no need to generate WF classes from the proto script, in csharp it is generated within a cproj declaration

**Pull request closed without merging**
